### ISSUE TITLE
purpur1.17.1 ERROR

### ISSUE THREAD

**Issue by yuankun1** [meiskam/PlayerHeads#28] opened 2021-07-25 08:22 UTC
[14:33:41] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to PlayerHeads v5.2.16-SNAPSHOT
java.lang.IllegalArgumentException: Creating a playerhead with a null or empty username is not possible with this method.
	at com.github.crashdemons.playerheads.SkullManager.PlayerSkull(SkullManager.java:186) ~[?:?]
	at org.shininet.bukkit.playerheads.PlayerHeadsListener.onHeadItemSpawn(PlayerHeadsListener.java:711) ~[?:?]
	at org.shininet.bukkit.playerheads.PlayerHeadsListener.onItemSpawnEvent(PlayerHeadsListener.java:692) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1296]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-1296]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1296]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1296]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callItemSpawnEvent(CraftEventFactory.java:761) ~[patched_1.17.1.jar:git-Purpur-1296]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:640) ~[patched_1.17.1.jar:git-Purpur-1296]
	at net.minecraft.server.level.ServerLevel.addEntity0(ServerLevel.java:1466) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1378) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.dropItem(CraftWorld.java:778) ~[patched_1.17.1.jar:git-Purpur-1296]
	at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.dropItem(CraftWorld.java:767) ~[patched_1.17.1.jar:git-Purpur-1296]
	at org.maxgamer.quickshop.shop.RealDisplayItem.spawn(RealDisplayItem.java:263) ~[?:?]
	at org.maxgamer.quickshop.shop.ContainerShop.checkDisplay(ContainerShop.java:331) ~[?:?]
	at org.maxgamer.quickshop.shop.ContainerShop.onLoad(ContainerShop.java:858) ~[?:?]
	at org.maxgamer.quickshop.listener.ChunkListener.lambda$onChunkLoad$0(ChunkListener.java:50) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1296]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1296]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1296]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1296]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1296]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1296]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1296]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by crashdemons** [comment] 2021-07-25 18:27
Based on this log, a head was dropped as an item in the world, which PH attempted to update
Can you provide any details about this head?  Was it a custom item (I'm presuming this case), a player's head, or a mob head?

A temporary solution to stop the error from appearing if it is spamming you will be to disabled `fixdroppedheads`, while I try to figure out why.

Thank you

**Comment by crashdemons** [comment] 2021-07-25 18:37
Nevermind, I can confirm this on "boring" (blank) playerheads
It doesn't appear to cause any issues despite the console spam, but I'll take a shot at fixing it.

**Comment by crashdemons** [comment] 2021-07-25 18:52
When it is finished building, you might try this snapshot version to see if it solves the issue.

https://ci.meme.tips/job/PlayerHeads-5.x/1148/

**Comment by crashdemons** [comment] 2021-08-15 05:18
Since there has not been any reply to this ticket for 20 days, this may soon be closed as fixed.
There is also an alpha for 5.2.17 pending approval on bukkitdev now.

**Closed as completed** 2021-09-28 22:52 UTC
Labels: bug, fix-submitted
